-- Seed pricing rows (run after solution_tier_pricing.sql and after those tiers exist in solution_tiers).
-- If inserts fail with FK errors, add the tiers in solution_tiers first (or temporarily drop the FK).

insert into public.solution_tier_pricing (
  solution_tier_id,
  offering_label,
  tier_label,
  scope,
  hours_client_services,
  hours_copy,
  hours_design,
  hours_web_dev,
  hours_video,
  hours_data,
  hours_paid_media,
  hours_hubspot,
  hours_other,
  total_hours,
  expected_effort_base_price,
  scope_risk,
  internal_coordination,
  client_revision_risk,
  risk_multiplier,
  risk_mitigated_base_price,
  strategic_value_score,
  strategic_value_multiplier,
  sell_price,
  standalone_sell_price,
  old_price,
  percent_change,
  requires_customization,
  taxable,
  notes,
  tags
) values
  (
    '3-3',
    'Customer Interviews (Up to 5)',
    'Basic',
    'Conduct up to 5 customer interviews',
    11,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    11,
    2310.00,
    0,
    1,
    0,
    1.1,
    2541.00,
    2,
    1.2,
    3100,
    3000,
    3165.00,
    '-2.05%',
    false,
    false,
    null,
    'Foundational, Discovery & Research'
  ),
  (
    '3-4',
    'Customer Interviews (Up to 10)',
    'Standard',
    'Conduct up to 10 customer interviews',
    18,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    18,
    3780.00,
    0,
    1,
    0,
    1.1,
    4158.00,
    2,
    1.2,
    5000,
    5000,
    null,
    'n/a',
    false,
    false,
    null,
    'Foundational, Discovery & Research'
  ),
  (
    '3-5',
    'Customer Interviews (Up to 15)',
    'Advanced',
    'Conduct up to 15 customer interviews',
    26,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    26,
    5460.00,
    0,
    1,
    0,
    1.1,
    6006.00,
    2,
    1.2,
    7300,
    7000,
    null,
    'n/a',
    false,
    false,
    null,
    'Foundational, Discovery & Research'
  ),
  (
    '3-1',
    'Clickstream Data Analysis',
    null,
    $scope3_1$(6) total Sparktoro datasets
users who visit your website (1)
users who visit your competitor's website (1)
persona-based searches (3)
custom audience (1)$scope3_1$,
    2.5,
    8.75,
    0,
    0,
    0,
    0,
    0,
    0,
    0.5,
    11.75,
    2467.50,
    0,
    1,
    1,
    1.1,
    2714.25,
    2,
    1.2,
    3300,
    3000,
    null,
    'n/a',
    false,
    false,
    $notes3_1$Does NOT include polished deck or presentation of findings
Can be scaled for additional segments$notes3_1$,
    'Foundational, Discovery & Research'
  ),
  (
    '3-2',
    'Clickstream Data Analysis - STANDALONE',
    null,
    $scope3_2$(6) total Sparktoro datasets
users who visit your website (1)
users who visit your competitor's website (1)
persona-based searches (3)
custom audience (1)$scope3_2$,
    6,
    10.5,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    17.5,
    3675.00,
    0,
    1,
    1,
    1.1,
    4042.50,
    2,
    1.2,
    4900,
    4500,
    null,
    'n/a',
    false,
    false,
    'Can be scaled for additional segments',
    'Discovery & Research'
  )
on conflict (solution_tier_id) do update set
  offering_label = excluded.offering_label,
  tier_label = excluded.tier_label,
  scope = excluded.scope,
  hours_client_services = excluded.hours_client_services,
  hours_copy = excluded.hours_copy,
  hours_design = excluded.hours_design,
  hours_web_dev = excluded.hours_web_dev,
  hours_video = excluded.hours_video,
  hours_data = excluded.hours_data,
  hours_paid_media = excluded.hours_paid_media,
  hours_hubspot = excluded.hours_hubspot,
  hours_other = excluded.hours_other,
  total_hours = excluded.total_hours,
  expected_effort_base_price = excluded.expected_effort_base_price,
  scope_risk = excluded.scope_risk,
  internal_coordination = excluded.internal_coordination,
  client_revision_risk = excluded.client_revision_risk,
  risk_multiplier = excluded.risk_multiplier,
  risk_mitigated_base_price = excluded.risk_mitigated_base_price,
  strategic_value_score = excluded.strategic_value_score,
  strategic_value_multiplier = excluded.strategic_value_multiplier,
  sell_price = excluded.sell_price,
  standalone_sell_price = excluded.standalone_sell_price,
  old_price = excluded.old_price,
  percent_change = excluded.percent_change,
  requires_customization = excluded.requires_customization,
  taxable = excluded.taxable,
  notes = excluded.notes,
  tags = excluded.tags,
  updated_at = now();
